name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia 'main' por el nombre de tu rama principal si es necesario

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      run: |
        mkdir public
        cp -r src/* ./public/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
